### ISSUE TITLE
pls don't use jQuery max version dependencies

### ISSUE THREAD

**Issue by kuehn-sba** [hashchange/jquery.isinview#2]
bower.json:
"jquery": ">=1.9.0 <3.1",

"<3.1" <- This will be a conflict everytime, when a newer jQuery will be used in own projects.
Can you pls remove it?

Greetings

**Comment by hashchange** [comment]
I have updated the version constraint for jQuery 3.1 - thanks for reminding me!

I won't remove the constraint, though. It's a trade-off. Semver is a promise, a way of saying "We'll do our best not to break your component when we publish a dot release". That's not quite the same as proven compatibility. jQuery has had its blunders in the past.

So rather than issuing a blank cheque for any dot release of jQuery, which will _most likely_ work, I verify each dot release by running the tests before I sign off on it, which _makes sure_ that it works. I figured that most people don't desperately depend on the few new features in a dot release, so the gain in reliability is worth the wait. On the other hand, I trust patch releases blindly, so bug fixes are available to everyone immediately.

That's how I handle key dependencies in all my components. I have been burnt in the past, and this strategy has worked well for me since.
